### ISSUE TITLE
Issue with Yoast SEO and Custom Contact Forms

### ISSUE THREAD

**Issue by kathycampbell** [tlovett1/custom-contact-forms#128] opened 2015-05-13 16:19 UTC
![customcontacterror](https://cloud.githubusercontent.com/assets/12432278/7615228/0e8f230e-f951-11e4-8c45-c18048ca7c3b.jpg)

I'm getting this error when both the Wordpress SEO plugin and Custom Contact Form plugins are activated. Don't know what needs to be done to fix it, but it's on all the websites I work with. I don't want to have to pick between them!

**Comment by tlovett1** [comment] 2015-05-14 02:36
Hmm works for me. What version of Yoast's plugin are you using? What other plugins are you running?

**Comment by kathycampbell** [comment] 2015-05-14 02:41
The newest version of all three. I've disabled all the plugins and turned them on one by one with Custom Contact and it shows up then when I go to edit/write either a new page or post. And is the Wordpress SEO plugin, that's authored by Yoast not the old "Yoast SEo for Wordpress" one.

**Comment by tlovett1** [comment] 2015-05-14 02:55
What version of WP?

**Comment by kathycampbell** [comment] 2015-05-14 03:00
4.2.2

**Comment by tlovett1** [comment] 2015-05-14 03:00
Can you email tlovett88 [at] gmail?

**Comment by tlovett1** [comment] 2015-05-14 03:03
Actually I reproduced the problem.

**Comment by kathycampbell** [comment] 2015-05-14 03:35
Great!

**Comment by tlovett1** [comment] 2015-05-14 13:59
This should be fixed by version 6.7.3

**Closed by tlovett1** 2015-05-14 13:59 UTC
