### ISSUE TITLE
Multiple email notifications get overlayed

### ISSUE THREAD

**Issue by wbower** [tlovett1/custom-contact-forms#220] opened 2016-01-13 17:59 UTC
I've setup 2 email notifications for a form, one goes to the admin email to notify of a new form submit and the second to the email address specified by the user as a confirmation of their entry. They get configured properly initially but at some point the Title, Subject and Email Content fields get set to the same values for both notifications. I've tried editing the one that was overlayed with the values of the other, and it gets overlayed again.

**Comment by tlovett1** [comment] 2016-01-14 05:21
Somehow I'm not able to reproduce. What browser?

**Comment by wbower** [comment] 2016-01-14 16:52
I'm using Chrome for the administration. I had tried IE but I was having other issues seeing all of the admin options.

I've attached some screen shots to show what happens. 

The first shot is after creating the first notification. It shows the Tile and Subject as "KVC Membership Confirmation"
The second shot is while adding the second notification and before saving the form/notification. It shows the Title "KVC Membership to Admin". The Subject (off the screen shot) was the same.
The third shot after saving the form/notification. It shows that the second notification has partially overlaid the first notification. The Title, Subject and Email text fields all get overlaid. The from and to email addresses are not affected.

I've tried editing the first notification to put it back to the way it was. Sometimes it will stick but as I make other changes to the form it will revert back to overlaying the notification.

**Comment by getcooking** [comment] 2016-01-15 07:17
I am having the exact same issue. I cannot seem to get the notifications to work where the admin receives a different notification from the email. I've recreated the notifications several times and each time get a different issue; it either sends the email's notification to both the email and the admin, or the admin's notification to both. Once, it also duplicated the email notification and the email received two notifications.

**Comment by tlovett1** [comment] 2016-01-17 06:58
Fixed in 7.4.2

**Closed by tlovett1** 2016-01-17 06:58 UTC

**Comment by wbower** [comment] 2016-01-17 18:40
Tested -- works great! Thanks for the quick response in fixing this issue.

**Comment by getcooking** [comment] 2016-01-18 19:51
Thank you! I appears to be working perfectly.

Cooking up fun!
*Carolyn Rehder and Kate Mendoza*
Owners, Sprouting Healthy Chefs, LLC
Certified Healthy Hands Cooking Instructors
(720) 507-5430 office
www.sproutinghealthychefs.com
